name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'daemon/Dockerfile'
      - 'web/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'daemon/Dockerfile'
      - 'web/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { folder: 'daemon', image: 'dmleet/deluge-daemon' }
          - { folder: 'web', image: 'dmleet/deluge-web' }
        include:
          - folder: 'daemon', image: 'dmleet/deluge-daemon', dockerfile: 'daemon/Dockerfile'
          - folder: 'web', image: 'dmleet/deluge-web', dockerfile: 'web/Dockerfile'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push ${{ matrix.image }}
        run: |
          docker build -f ${{ matrix.folder }}/Dockerfile -t ${{ matrix.image }}:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ matrix.image }}:latest